# Generated by Django 2.0.1 on 2018-08-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_min_size', models.IntegerField(blank=True, verbose_name='数量最小値')),
                ('order_digit', models.IntegerField(blank=True, verbose_name='数量の桁数')),
                ('fee_rate', models.IntegerField(blank=True, verbose_name='取引手数料のレート(%)')),
                ('buy_unit', models.IntegerField(blank=True, verbose_name='購入単位')),
                ('profit', models.IntegerField(blank=True, verbose_name='価格差')),
            ],
        ),
        migrations.CreateModel(
            name='BbApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='APIキー')),
                ('api_secret', models.CharField(max_length=255, verbose_name='APIシークレット')),
                ('api_url', models.CharField(max_length=255, verbose_name='APIURL')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.IntegerField(verbose_name='取引所コード')),
                ('name', models.CharField(max_length=255, verbose_name='取引所名')),
                ('status', models.BooleanField(verbose_name='ステータス')),
            ],
        ),
        migrations.AddField(
            model_name='bbapi',
            name='exchange_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BbApiConfig', to='tradeApp.Exchange', verbose_name='取引所'),
        ),
        migrations.AddField(
            model_name='apitrade',
            name='exchange_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ApiTradeConfig', to='tradeApp.Exchange', verbose_name='取引所'),
        ),
    ]
